import '../../global.css';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: 'Welcome to guard-shield-tauri',
  description: 'Generated by create-nx-workspace',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  );
}
